services:
  app:
    container_name: app
    build: ./app
    ports:
      - "55173:55173"
    volumes:
      - ./app:/app
      - /app/node_modules
    restart: always
    depends_on:
      - api
  api:
    container_name: api
    build: ./api
    ports:
      - "33000:33000"
    env_file:
      - ./api/.env
    # environment:
    #   - DATABASE_URL=postgresql://postgres:password@db:5432/vinyls_addict
    #   - PORT=33000
    command: pnpm run nodemon
    volumes:
      - ./api:/api
      - /api/node_modules
    restart: always
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:18.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vinyls_addict
      DATABASE_URL: postgresql://postgres:password@db:5432/vinyls_addict
      
    ports:
      - "55432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    restart: always
  prisma-studio:
    container_name: prisma-studio
    build: ./api 
    command: npx prisma studio --port 5555 --browser none
    environment:
      - POSTGRES_URL=postgresql://postgres:password@db:5432/vinyls_addict
    ports:
      - "55555:5555"
    volumes:
      - ./api:/api
    working_dir: /api
    restart: always
    depends_on:
      - db
volumes:
  db_data:    
      